[package]
name = "nom-date-parsers"
authors = ["Сырцев Вадим Игоревич <syrtcevvi@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
nom = "7.1.3"
rstest = "0.21.0"
thiserror = "1.0.61"

[dev-dependencies]
pretty_assertions = "1.4.0"
